### ISSUE TITLE
Some issues while running Virdetect

### ISSUE THREAD

**Issue by davidjones1993** [dmarron/virdetect#4]
Hi,
I am running Virdetect on my RNA-Seq reads. I had previously aligned the reads to human ref genome and had saver the unaligned reads as fastq while running STAR. So I have skipped the steps which extract the unaligned reads from the sam file and convert to fastq. My genome here to which the alignment was done is hg19. I have used your reference hg38.virus.masked genome. I hope it won't be a problem as the genomic sequences are same be it hg19 or hg38

I have generated th viral.read.counts.txt file and it just contains a single line of 1894 values, most of which are 0s. Only 5 are non-zero. However since this file contains no header, I can't infer anything from this.

Next I used your scipts to generate the viralRTable.txt file. In this command what should I enter as <virus name> ? I entered retrovirus and it worked fine but do I need to provide the virus names exactly as given in the reference file?

Lastly, I ran the file in R. It gave the following errors 3 times
Error in '[.data.frame'(mcf, ,c(3:6)) : undefined columns selected
It still generated the plot.

I am attaching the viralreadcounts.txt, viralrtable.txt and the R coverage plot.

I heartily request you to take some time and help me with these issues. Thanks a ton.
[S1viralReadCounts.txt](https://github.com/dmarron/virdetect/files/4865329/S1viralReadCounts.txt)
[viralRTable.txt](https://github.com/dmarron/virdetect/files/4865330/viralRTable.txt)
![Coverage_plot_retrovirus](https://user-images.githubusercontent.com/67751347/86380566-db1fa300-bca9-11ea-8968-69593712325d.png)

**Comment by dmarron** [comment]
Hi David,

I hope that I can help you with your questions.

> I have used your reference hg38.virus.masked genome. I hope it won't be a problem as the genomic sequences are same be it hg19 or hg38

Yes, I don't think it will be a problem to use the hg38 masked genome.

> However since this file contains no header, I can't infer anything from this.

Each column of the output refers to the @SQ headers of the virus aligned bam file. (So the first column with data is the first virus strain the bam file).  The following commands can be used to create a header from a given bam file:

    samtools view -h out.bam | grep "^@SQ" | cut -f 2 > temp.txt
    tr -s '\\n' '\\t' < temp.txt > temp2.txt
    echo "sample" > temp3.txt
    paste temp3.txt temp2.txt | sed 's/[ \t]*\$//' > header.txt

> Next I used your scipts to generate the viralRTable.txt file. In this command what should I enter as ?

I'm not completely sure what you are asking, but you can specify the virus name in the virus_name parameter and it should match the strain name you are trying to visualize in the bam file and the reference file.  It doesn't have to match exactly, but should be an exact subset of the actual strain name (which is why retrovirus works).

> Lastly, I ran the file in R. It gave the following errors 3 times

I am not sure why you are getting this error, could you send me the exact R command you used?  The error may not be a concern, since the visualization looks correct to me based on the attached viralRTable from a quick check.

Best,
David
