### ISSUE TITLE
For human data the workflow issue

### ISSUE THREAD

**Issue by qianwenluo** [dmarron/virdetect#5]
I run the code and use java/1.8:
java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:countStarViralAlignments.jar countStarViralAlignments sample_name STAR_virus_Aligned.out.sam viralReadCounts.txt

and got the error message:

Exception in thread "main" java.lang.NoClassDefFoundError: net/sf/samtools/SAMFileReader
	at countStarViralAlignments.main(countStarViralAlignments.java:46)
Caused by: java.lang.ClassNotFoundException: net.sf.samtools.SAMFileReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more

Could you please help me understand what I am doing wrong?
Thank you in advance.

Qianwen

**Comment by dmarron** [comment]
Hi Qianwen,

I am not sure why are are getting this error, I downloaded picard-1.92.jar, sam-1.92.jar, and countStarViralAlignments.jar just now and ran them with the command java -Xmx4G -cp picard-1.92.jar:sam-1.92.jar:countStarViralAlignments.jar countStarViralAlignments and it worked for me.  The error you are getting implies that it does not recognize picard-1.92.jar and sam-1.92.jar, since I get that exact error if I run it with just the countStarViralAlignments.jar.  Could there be a typo with one or more of the ":" or jar names in your command?  Are the picard-1.92.jar and sam-1.92.jar files in the directory you are running from?

If the command looks correct, I would suggest downloading countStarViralAlignments.java from the src directory of the github and trying to compile it with javac and then run it from the .class file.  You will need to specify picard-1.92.jar and sam-1.92.jar in order to compile it.  If that gives you an error, please let me know.

Best,
David

**Comment by qianwenluo** [comment]
Hi David,

I tried picard-1.92.jar and sam-1.92.jar under virdetect/java/java-src/ and it works. Thank you so much!!


Thanks,
Qianwen
