### ISSUE TITLE
Reads mapped to retrovirus but no in human genome

### ISSUE THREAD

**Issue by davidjones1993** [dmarron/virdetect#6]
Hi,
   This is not an issue per se, just a question I have. I have mapped the unaligned portion of my reads to the virus_masked.fa file. There I have obtained about 1000 reads per sample that have mapped to "Human_endogenous_retrovirus_K113". I have read that this virus comprises about 8% of the human genome. I have taken some of the reads that have mapped to the retrovirus and have BLAT them to human genome to find that they correspond to several regions in the human genome with 100% identity. 

So my question is why did these reads not map to the human genome when aligned originally with STAR? I was hoping you could help me with this.

**Comment by sararselitsky** [comment]
Human endogenous retrovirus K113 is a retrovirus that most or all people have, but is not part of human reference genome. However, this virus has elements with high homology to other endogenous retroviruses, which is why you are seeing reads that map to it, map to the human genome. These reads might have been unmapped due to multimapping.
